name: be_fast
description: "Delivery Service"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.5
  http: ^1.1.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  socket_io_client: ^2.0.3+1
  url_launcher: ^6.2.4
  firebase_storage: ^11.6.7
  audioplayers: ^5.2.1
  flutter_native_splash: ^2.3.9
  sliding_up_panel: ^2.0.0+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1C1D33"
  remove_alpha_ios: true

flutter_native_splash:
  image: assets/images/logo.png
  color: "#1C1D33"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - .env
